/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package electronic.voting.machine;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


/**
 *
 * @author user
 */
public class VOTINGSCREEN extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ps;
    public static String x;

    /**
     * Creates new form VOTINGSCREEN
     */
    public VOTINGSCREEN() {
        initComponents();
        jLabel9.setText(Login.userName);
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/evm","root","lakshay@99");
        }
        catch(Exception ex)
        {
            
        }
    }
    
        
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bjp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        congress = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        aap = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cpi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bsp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ncp = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        sp = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nota = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electronic/voting/machine/bjp.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        bjp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bjp.setForeground(new java.awt.Color(255, 0, 0));
        bjp.setText("BJP");
        bjp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bjpActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electronic/voting/machine/congress.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        congress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        congress.setForeground(new java.awt.Color(0, 102, 51));
        congress.setText("CONGRESS");
        congress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congressActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electronic/voting/machine/aap_1.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        aap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aap.setText("AAP");
        aap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aapActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electronic/voting/machine/cpi1.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        cpi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cpi.setForeground(new java.awt.Color(102, 0, 0));
        cpi.setText("CPI");
        cpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpiActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electronic/voting/machine/bsp1.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        bsp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsp.setForeground(new java.awt.Color(0, 0, 204));
        bsp.setText("BSP");
        bsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bspActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electronic/voting/machine/ncp1.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        ncp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ncp.setForeground(new java.awt.Color(255, 51, 0));
        ncp.setText("NCP");
        ncp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ncpActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electronic/voting/machine/sp1.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        sp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sp.setForeground(new java.awt.Color(0, 102, 51));
        sp.setText("SP");
        sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electronic/voting/machine/nota1.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        nota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nota.setForeground(new java.awt.Color(102, 102, 102));
        nota.setText("NOTA");
        nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cpi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bjp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ncp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(congress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(bjp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(congress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(cpi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(ncp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(nota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void congressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congressActionPerformed
        // TODO add your handling code here:
                 try
        {
            String party_name="CONGRESS";
            choice(party_name);
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_congressActionPerformed

    private void bspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bspActionPerformed
        // TODO add your handling code here:
                 try
        {
            String party_name="BSP";
            choice(party_name);
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_bspActionPerformed

    private void spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spActionPerformed
        // TODO add your handling code here:
               try
        {
            String party_name="SP";
            choice(party_name);
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_spActionPerformed

    private void bjpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjpActionPerformed
        // TODO add your handling code here:
        try
        {
            String party_name="BJP";
            choice(party_name);
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_bjpActionPerformed

    private void aapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aapActionPerformed
        // TODO add your handling code here:
                 try
        {
            String party_name="AAP";
            choice(party_name);
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_aapActionPerformed

    private void cpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpiActionPerformed
        // TODO add your handling code here:
                 try
        {
            String party_name="CPI";
            choice(party_name);
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_cpiActionPerformed

    private void ncpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ncpActionPerformed
        // TODO add your handling code here:
                 try
        {
            String party_name="NCP";
            choice(party_name);
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_ncpActionPerformed

    private void notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaActionPerformed
        // TODO add your handling code here:
                 try
        {
            String party_name="NOTA";
            choice(party_name);
        }
                 
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_notaActionPerformed
public void choice(String partyname){
    try
    {
        String sql="insert into vote values(?,?)";
        ps=con.prepareStatement(sql);
        ps.setString(1,x);
        System.out.println(x);
        ps.setString(1,partyname);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Congratulations, you have casted your VOTE");
        this.setVisible(false);
    }
    catch(Exception ex){
        System.out.println(ex);
    }
}

    VOTINGSCREEN(String aadharnumber) {
        
        x=aadharnumber;
        System.out.println(x);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VOTINGSCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VOTINGSCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VOTINGSCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VOTINGSCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VOTINGSCREEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aap;
    private javax.swing.JButton bjp;
    private javax.swing.JButton bsp;
    private javax.swing.JButton congress;
    private javax.swing.JButton cpi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton ncp;
    private javax.swing.JButton nota;
    private javax.swing.JButton sp;
    // End of variables declaration//GEN-END:variables
}
